### ISSUE TITLE
/action/exec is not executable

### ISSUE THREAD

**Issue by chikamichi** [apache/openwhisk-runtime-docker#65]
Hi,

Following along http://jamesthom.as/blog/2017/01/16/openwhisk-docker-actions/ (section _Running Locally_), I've been able to quickly iterate on a custom action/runtime, but for a specific issue: /action/exec ends up not being executable as a result of `initCodeFromZip`.

The local file is 0755, but once pushed within the container as part of a base64 zip, it's 0544 (or 0744 I don't remember :see_no_evil:) and belongs to the root user. Therefore POST /init kept failing [on this line](https://github.com/apache/incubator-openwhisk-runtime-docker/blob/766419cc6ee59b74ccdd91652c3d41bb47abdc89/core/actionProxy/actionproxy.py#L104), specifically the `os.X_OK` check (which was not obvious at first but the local dev setup turned out great to debug as well).

To work around the issue, I edited [both `initCode*` functions](https://github.com/apache/incubator-openwhisk-runtime-docker/blob/766419cc6ee59b74ccdd91652c3d41bb47abdc89/core/actionProxy/actionproxy.py#L187-L203) to add `os.chmod(self.source, 0755)` right before their return statements (could be refactored to DRY things up):

``` diff
     # initialize code from inlined string
     def initCodeFromString(self, message):
         with codecs.open(self.source, 'w', 'utf-8') as fp:
             fp.write(message['code'])
+            os.chmod(self.source, 0755)
         return True

     # initialize code from base64 encoded archive
     def initCodeFromZip(self, message):
         try:
             bytes = base64.b64decode(message['code'])
             bytes = io.BytesIO(bytes)
             archive = zipfile.ZipFile(bytes)
             archive.extractall(self.zipdest)
             archive.close()
+            os.chmod(self.source, 0755)
             return True
         except Exception as e:
             print('err', str(e))
             return False
```

I'd like to believe it's a safe move to make, but I'm not sure really. What do you maintainers think? If it sounds about right, I could create a quick-win PR for this of course.

Dev setup: fresh Debian Stretch install, Docker version 18.06.1-ce, using openwhisk/dockerskeleton:latest as build image. Dev source code [available here](https://github.com/codemiam/faas/pull/1/commits/31cc1708daa797bae0d60411c6c3d68234b91774) (specifically the Dockerfile).

**Comment by rabbah** [comment]
The file that's already in the container should have `x` permissions - and unzipping to overwrites should preserve that permission. Can you confirm that `/action/exec` (The stub/placeholder in place) is executable before running the function?
